// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TecFlow.Database;

#nullable disable

namespace TecFlow.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922250000_AddShortAffiliateLinkAffiliateUrlAndAccount")]
    partial class AddShortAffiliateLinkAffiliateUrlAndAccount
    {
    }
}
