// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TecFlow.Database;

#nullable disable

namespace TecFlow.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924010000_UniqueMarketplaceAccountTrackingIdPerPlatform")]
    partial class UniqueMarketplaceAccountTrackingIdPerPlatform
    {
    }
}
