// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TecFlow.Database;

#nullable disable

namespace TecFlow.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922240000_AddMarketplaceAccountOptionalCredentialsPg")]
    partial class AddMarketplaceAccountOptionalCredentialsPg
    {
    }
}
